min_replicates: 7
min_disp: 0.00000001
max_disp: 10.0
grid_batch_size: 250
grid_depth: 3
grid_length: 100
num_jobs: 8
min_mu: 0.5
beta_tol: 0.00000001
max_beta: 30.0
irls_num_iter: 20
joblib_backend: "loky"
joblib_verbosity: 0
irls_batch_size: 100
independent_filter: true
alpha: 0.05
PQN_c1: 0.0001
PQN_ftol: 0.0000001
PQN_num_iters_ls: 20
PQN_num_iters: 100
PQN_min_mu: 0.0
refit_cooks: true
cooks_filter: true
save_layers_to_disk: false
trimmed_mean_num_iter: 40
lfc_null: 0.0
